In [1]:
import numpy as np
import h5py

In [75]:
np.sqrt(33.45*33.45+2.7*2.7)

33.55879169457685

In [71]:
np.arccos(0.99)

0.1415394733244273

In [72]:
np.arccos(0.99)*180/np.pi

8.109614455994183

In [73]:
# Rotation matrix
R=([1/2*(1+1/np.sqrt(3)), -1/2*(1-1/np.sqrt(3)), 1/np.sqrt(3)],
   [-1/2*(1-1/np.sqrt(3)), 1/2*(1+1/np.sqrt(3)), 1/np.sqrt(3)],
   [-1/np.sqrt(3), -1/np.sqrt(3), 1/np.sqrt(3)])
R

([0.7886751345948129, -0.21132486540518708, 0.5773502691896258],
 [-0.21132486540518708, 0.7886751345948129, 0.5773502691896258],
 [-0.5773502691896258, -0.5773502691896258, 0.5773502691896258])

In [74]:
alpha=0.99
g=[0, np.sin(alpha), np.cos(alpha)]
g

[0, 0.8360259786005205, 0.5486898605815875]

In [68]:
np.matmul(R,g)

array([ 0.14011316,  0.97613914, -0.16589359])

In [69]:
np.matmul(R, np.array(R).T)

array([[1.00000000e+00, 1.66533454e-16, 5.55111512e-17],
       [1.66533454e-16, 1.00000000e+00, 5.55111512e-17],
       [5.55111512e-17, 5.55111512e-17, 1.00000000e+00]])

In [70]:
np.linalg.det(R)

1.0000000000000002

In [11]:
(108*50)/49.15

109.8677517802645

In [76]:
gx=1/np.sqrt(3)
gy=1/np.sqrt(3)
gz=1/np.sqrt(3)

y = ([gx**2-1, gx**2, gx**2],
   [gy**2, gy**2-1, gy**2],
   [gz**2, gz**2, gz**2-1])

In [77]:
u, s, vh = np.linalg.svd(y)
null_space = np.compress(s <= 1e-6, vh, axis=0)
null_space

array([[-0.57735027, -0.57735027, -0.57735027]])

In [78]:
gx, gy, gz = np.matmul(R,g)

y = ([gx**2-1, gx**2, gx**2],
   [gy**2, gy**2-1, gy**2],
   [gz**2, gz**2, gz**2-1])

In [79]:
u, s, vh = np.linalg.svd(y)
null_space = np.compress(s <= 1e-6, vh, axis=0)
null_space

array([[-0.02059023, -0.99937125, -0.0288644 ]])

In [80]:
np.sqrt(null_space/null_space.min())

array([[0.1435381 , 1.        , 0.16994871]])

In [81]:
np.round(np.sqrt(null_space/null_space.min()))*np.array([1, 1, -1])

array([[ 0.,  1., -0.]])

In [38]:
np.sin(60)

-17.464362139918286